# .github/workflows/ssh_deploy.yml

name: Deploy Eleventy via SSH

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      # so your workflow can access it
      - uses: actions/checkout@master

      # use node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build

      - name: Upload files
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          local-dir: "_site/"
          server-dir: "${{ secrets.REMOTE_DIR }}"

      # # Copying files and artifacts via SSH
      # - name: Copying files to server
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.REMOTE_HOST }}
      #     username: ${{ secrets.REMOTE_USER }}
      #     key: ${{ secrets.SSH_KEY }}
      #     passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
      #     rm: true
      #     source: "_site/"
      #     target: "${{ secrets.REMOTE_DIR }}"
